// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://wfkb5g4zqvdlrlzeonnp7tmx5u.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fdyukjxg7nh6bhlj2nipmmd2ce",
    "aws_cognito_identity_pool_id": "eu-west-1:23a75f17-436c-4223-a8d7-c013e0ee7f45",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_il481QHcj",
    "aws_user_pools_web_client_id": "1e67ddhl3116o77q9m8astk61a"
};


export default awsmobile;
